name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version: [25.3, 26.3, 27.2, 28.2, 29.4]
        experimental: [false]
        include:
          - os: ubuntu-latest
            emacs-version: snapshot
            experimental: true

    steps:
      - name: setenv
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: conao3/setup-cask@master
        with:
          version: snapshot

      - name: install
        run: |
          export GPG_HOME="$(pwd)/.cask/${{ matrix.emacs-version }}/elpa/gnupg"; \
          mkdir -p $GPG_HOME && gpg --homedir $GPG_HOME --receive-keys 066DAFCB81E42C40; \
          cask install; ls -la "./.cask/${{ matrix.emacs-version }}"


      - name: test
        run: cask exec ert-runner

      - name: build
        run: cask build

      - name: package
        run: cask package

